insert into entrant (city, district, school, User_idUser, isBlocked) values ('Oklahoma City', 'Oklahoma', 'School #1', 1, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Stamford', 'Connecticut', 'School #2', 2, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Yakima', 'Washington', 'School #3', 3, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('New Orleans', 'Louisiana', 'School #4', 4, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Scottsdale', 'Arizona', 'School #5', 5, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Fayetteville', 'North Carolina', 'School #6', 6, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Dallas', 'Texas', 'School #7', 7, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Roanoke', 'Virginia', 'School #8', 8, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Washington', 'District of Columbia', 'School #9', 9, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Waco', 'Texas', 'School #10', 10, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Omaha', 'Nebraska', 'School #11', 11, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Oakland', 'California', 'School #12', 12, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Colorado Springs', 'Colorado', 'School #13', 13, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Madison', 'Wisconsin', 'School #14', 14, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Hartford', 'Connecticut', 'School #15', 15, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Wichita Falls', 'Texas', 'School #16', 16, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Richmond', 'Virginia', 'School #17', 17, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Albany', 'New York', 'School #18', 18, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Hollywood', 'Florida', 'School #19', 19, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Montgomery', 'Alabama', 'School #20', 20, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Corpus Christi', 'Texas', 'School #21', 21, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Tulsa', 'Oklahoma', 'School #22', 22, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Atlanta', 'Georgia', 'School #23', 23, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Jacksonville', 'Florida', 'School #24', 24, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Atlanta', 'Georgia', 'School #25', 25, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Brooklyn', 'New York', 'School #26', 26, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('New York City', 'New York', 'School #27', 27, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Toledo', 'Ohio', 'School #28', 28, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Omaha', 'Nebraska', 'School #29', 29, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Fort Wayne', 'Indiana', 'School #30', 30, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Louisville', 'Kentucky', 'School #31', 31, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Eugene', 'Oregon', 'School #32', 32, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Columbus', 'Ohio', 'School #33', 33, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Sacramento', 'California', 'School #34', 34, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Valley Forge', 'Pennsylvania', 'School #35', 35, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Tyler', 'Texas', 'School #36', 36, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Raleigh', 'North Carolina', 'School #37', 37, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Miami', 'Florida', 'School #38', 38, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Austin', 'Texas', 'School #39', 39, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Birmingham', 'Alabama', 'School #40', 40, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Atlanta', 'Georgia', 'School #41', 41, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Lancaster', 'Pennsylvania', 'School #42', 42, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Springfield', 'Illinois', 'School #43', 43, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Van Nuys', 'California', 'School #44', 44, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Salt Lake City', 'Utah', 'School #45', 45, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Springfield', 'Massachusetts', 'School #46', 46, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Atlanta', 'Georgia', 'School #47', 47, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Fort Collins', 'Colorado', 'School #48', 48, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Cleveland', 'Ohio', 'School #49', 49, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Orlando', 'Florida', 'School #50', 50, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Washington', 'District of Columbia', 'School #51', 51, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Denver', 'Colorado', 'School #52', 52, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Cincinnati', 'Ohio', 'School #53', 53, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Van Nuys', 'California', 'School #54', 54, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Fresno', 'California', 'School #55', 55, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Aurora', 'Colorado', 'School #56', 56, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Virginia Beach', 'Virginia', 'School #57', 57, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Richmond', 'Virginia', 'School #58', 58, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Detroit', 'Michigan', 'School #59', 59, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Raleigh', 'North Carolina', 'School #60', 60, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Tampa', 'Florida', 'School #61', 61, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Nashville', 'Tennessee', 'School #62', 62, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('New York City', 'New York', 'School #63', 63, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Baltimore', 'Maryland', 'School #64', 64, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Shawnee Mission', 'Kansas', 'School #65', 65, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Louisville', 'Kentucky', 'School #66', 66, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Oklahoma City', 'Oklahoma', 'School #67', 67, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Philadelphia', 'Pennsylvania', 'School #68', 68, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('New York City', 'New York', 'School #69', 69, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Charlottesville', 'Virginia', 'School #70', 70, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Columbus', 'Ohio', 'School #71', 71, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Houston', 'Texas', 'School #72', 72, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Saint Cloud', 'Minnesota', 'School #73', 73, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Indianapolis', 'Indiana', 'School #74', 74, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Newport Beach', 'California', 'School #75', 75, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Henderson', 'Nevada', 'School #76', 76, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Dallas', 'Texas', 'School #77', 77, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('San Diego', 'California', 'School #78', 78, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Hyattsville', 'Maryland', 'School #79', 79, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Sacramento', 'California', 'School #80', 80, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Louisville', 'Kentucky', 'School #81', 81, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Brockton', 'Massachusetts', 'School #82', 82, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Bethlehem', 'Pennsylvania', 'School #83', 83, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Pittsburgh', 'Pennsylvania', 'School #84', 84, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Rochester', 'New York', 'School #85', 85, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Boise', 'Idaho', 'School #86', 86, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Orlando', 'Florida', 'School #87', 87, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('New York City', 'New York', 'School #88', 88, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Norwalk', 'Connecticut', 'School #89', 89, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Chicago', 'Illinois', 'School #90', 90, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Harrisburg', 'Pennsylvania', 'School #91', 91, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Tyler', 'Texas', 'School #92', 92, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Dulles', 'Virginia', 'School #93', 93, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Cincinnati', 'Ohio', 'School #94', 94, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Arlington', 'Texas', 'School #95', 95, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('San Antonio', 'Texas', 'School #96', 96, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Louisville', 'Kentucky', 'School #97', 97, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Louisville', 'Kentucky', 'School #98', 98, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Salt Lake City', 'Utah', 'School #99', 99, 0);
insert into entrant (city, district, school, User_idUser, isBlocked) values ('Terre Haute', 'Indiana', 'School #100', 100, 0);
