INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Автоматика и приборостроения', 'DEPARTMENT OF AUTOMATICS AND INSTRUMENT', 20,10);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Бизнес и финансы', 'DEPARTMENT OF BUSINESS AND FINANCE', 30,20);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Инженерно-физический', 'DEPARTMENT FOR ENGINEERING PHYSICS', 40,30);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Интегральной подготовки', 'DEPARTMENT OF INTEGRAL EDUCATION', 50,40);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Интегрированные технологии и химическая техника', 'DEPARTMENT OF THE INTEGRAL TECHNOLOGY AND APPLIED CHEMISTRY', 60,50);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Информатика и управление', 'DEPARTMENT FOR COMPUTER SCIENCE AND MANAGEMENT', 70,60);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Компьютерные и информационные технологии', 'DEPARTMENT OF COMPUTER SCIENCE AND INFORMATION TECHNOLOGIES', 80,70);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Машиностроительный', 'DEPARTMENT OF MECHANICAL ENGINEERING', 90,80);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Международного образования', 'DEPARTMENT OF INTERNATIONAL EDUCATION', 100,90);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Механико-технологический', 'MECHANICAL & TECHNOLOGICAL DEPARTMENT', 15,5);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Немецкий технический', 'GERMAN TECHNICAL DEPARTMENT', 25,15);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Технологии неорганических веществ', 'DEPARTMENT TECHNOLOGY OF INORGANIC SUBSTANCES', 35,25);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Технологии органических веществ', 'DEPARTMENT TECHNOLOGY OF ORGANIC SUBSTANCES', 45,35);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Транспортного машиностроения', 'DEPARTMENT FOR TRANSPORT ENGINEERING INDUSTRY', 55,45);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Физико-технический', 'PHYSICO-TECHNICAL DEPARTMENT', 65,55);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Экономическая информатика и менеджмент', 'DEPARTMENT OF ECONOMIC INFORMATION SCIENCE AND MANAGEMENT', 75,65);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Экономический', 'ECONOMIC DEPARTMENT', 85,75);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Электромашиностроительный', 'ELECTRIC MACHINE INDUSTRY', 95,85);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Электроэнергетический', 'DEPARTMENT OF ELECTRIC POWER STATIONS', 105,95);
INSERT INTO university_admission.faculty(name_ru, name_eng,total_seats,budget_seats) VALUES ('Энергомашиностроительный', 'ENERGY MACHINE INDUSTRY', 115,105);