INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Автоматика и приборостроения',20,10);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Бизнес и финансы',30,20);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Инженерно-физический',40,30);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Интегральной подготовки',50,40);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Интегрированные технологии и химическая техника',60,50);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Информатика и управление',70,60);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Компьютерные и информационные технологии',80,70);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Машиностроительный',90,80);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Международного образования',100,90);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Механико-технологический',15,5);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Немецкий технический',25,15);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Технологии неорганических веществ',35,25);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Технологии органических веществ',45,35);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Транспортного машиностроения',55,45);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Физико-технический',65,55);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Экономическая информатика и менеджмент',75,65);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Экономический',85,75);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Электромашиностроительный',95,85);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Электроэнергетический',105,95);
INSERT INTO university_admission.faculty(name,total_seats,budget_seats) VALUES ('Энергомашиностроительный',115,105);